// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: GUI_vesc_controller

#ifndef _UI_COMP_PANELNAVIGATION_H
#define _UI_COMP_PANELNAVIGATION_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PanelNavigation
#define UI_COMP_PANELNAVIGATION_PANELNAVIGATION 0
#define UI_COMP_PANELNAVIGATION_BUTTONHOME 1
#define UI_COMP_PANELNAVIGATION_BUTTONSETTINGS 2
#define UI_COMP_PANELNAVIGATION_BUTTONINFO 3
#define _UI_COMP_PANELNAVIGATION_NUM 4
lv_obj_t *ui_PanelNavigation_create(lv_obj_t *comp_parent);
void ui_event_comp_PanelNavigation_ButtonHome( lv_event_t * e);
void ui_event_comp_PanelNavigation_ButtonSettings( lv_event_t * e);
void ui_event_comp_PanelNavigation_ButtonInfo( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
