// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: GUI_vesc_controller

#include "ui.h"

void ui_event_comp_PanelNavigation_ButtonHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_PanelNavigation = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}

void ui_event_comp_PanelNavigation_ButtonSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_PanelNavigation = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
}
}

void ui_event_comp_PanelNavigation_ButtonInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_PanelNavigation = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Info, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Info_screen_init);
}
}

// COMPONENT PanelNavigation

lv_obj_t *ui_PanelNavigation_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_PanelNavigation;
cui_PanelNavigation = lv_obj_create(comp_parent);
lv_obj_set_height( cui_PanelNavigation, 50);
lv_obj_set_width( cui_PanelNavigation, lv_pct(98));
lv_obj_set_x( cui_PanelNavigation, 0 );
lv_obj_set_y( cui_PanelNavigation, -8 );
lv_obj_set_align( cui_PanelNavigation, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(cui_PanelNavigation,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_PanelNavigation, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_PanelNavigation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_ButtonHome;
cui_ButtonHome = lv_imgbtn_create(cui_PanelNavigation);
lv_imgbtn_set_src(cui_ButtonHome, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png, NULL);
lv_imgbtn_set_src(cui_ButtonHome, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png, NULL);
lv_obj_set_width( cui_ButtonHome, 34);
lv_obj_set_height( cui_ButtonHome, 35);
lv_obj_set_align( cui_ButtonHome, LV_ALIGN_CENTER );
lv_obj_set_style_transform_zoom(cui_ButtonHome, 256, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(cui_ButtonHome, 300, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_t *cui_ButtonSettings;
cui_ButtonSettings = lv_imgbtn_create(cui_PanelNavigation);
lv_imgbtn_set_src(cui_ButtonSettings, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_settings_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png, NULL);
lv_imgbtn_set_src(cui_ButtonSettings, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_settings_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png, NULL);
lv_obj_set_width( cui_ButtonSettings, 34);
lv_obj_set_height( cui_ButtonSettings, 35);
lv_obj_set_align( cui_ButtonSettings, LV_ALIGN_CENTER );
lv_obj_set_style_transform_zoom(cui_ButtonSettings, 256, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(cui_ButtonSettings, 300, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_t *cui_ButtonInfo;
cui_ButtonInfo = lv_imgbtn_create(cui_PanelNavigation);
lv_imgbtn_set_src(cui_ButtonInfo, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_info_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png, NULL);
lv_imgbtn_set_src(cui_ButtonInfo, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_info_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png, NULL);
lv_obj_set_width( cui_ButtonInfo, 34);
lv_obj_set_height( cui_ButtonInfo, 35);
lv_obj_set_align( cui_ButtonInfo, LV_ALIGN_CENTER );
lv_obj_set_style_transform_zoom(cui_ButtonInfo, 256, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(cui_ButtonInfo, 300, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANELNAVIGATION_NUM);
children[UI_COMP_PANELNAVIGATION_PANELNAVIGATION] = cui_PanelNavigation;
children[UI_COMP_PANELNAVIGATION_BUTTONHOME] = cui_ButtonHome;
children[UI_COMP_PANELNAVIGATION_BUTTONSETTINGS] = cui_ButtonSettings;
children[UI_COMP_PANELNAVIGATION_BUTTONINFO] = cui_ButtonInfo;
lv_obj_add_event_cb(cui_PanelNavigation, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_PanelNavigation, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_ButtonHome, ui_event_comp_PanelNavigation_ButtonHome, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_ButtonSettings, ui_event_comp_PanelNavigation_ButtonSettings, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_ButtonInfo, ui_event_comp_PanelNavigation_ButtonInfo, LV_EVENT_ALL, children);
ui_comp_PanelNavigation_create_hook(cui_PanelNavigation);
return cui_PanelNavigation; 
}

