// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: GUI_vesc_controller

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern void ui_event_ArcSpeed( lv_event_t * e);
extern lv_obj_t *ui_ArcSpeed;
extern lv_obj_t *ui_Speed;
extern lv_obj_t *ui_Batterlevel;
extern lv_obj_t *ui_IMGBattery;
extern lv_obj_t *ui_IMGDistance;
extern lv_obj_t *ui_Distance;
extern lv_obj_t *ui_SwitchEnable;
extern lv_obj_t *ui_CompasAngle;
extern void ui_event_SliderPotPosition( lv_event_t * e);
extern lv_obj_t *ui_SliderPotPosition;
extern lv_obj_t *ui_PotPosition;
extern lv_obj_t *ui_InfoText;
extern lv_obj_t *ui_SSIDInfo;
extern lv_obj_t *ui_PassInfo;
extern lv_obj_t *ui_NetworkInfo;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Home;
extern lv_obj_t *uic_ArcSpeed;
extern lv_obj_t *uic_Batterlevel;
extern lv_obj_t *uic_IMGBattery;
extern lv_obj_t *uic_IMGDistance;
extern lv_obj_t *uic_Distance;
extern lv_obj_t *uic_SwitchEnable;
extern lv_obj_t *uic_CompasAngle;
extern lv_obj_t *uic_SliderPotPosition;
extern lv_obj_t *uic_PotPosition;
extern lv_obj_t *uic_InfoText;
extern lv_obj_t *uic_SSIDInfo;
extern lv_obj_t *uic_PassInfo;
extern lv_obj_t *uic_NetworkInfo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

