// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: GUI_vesc_controller

#ifndef _GUI_VESC_CONTROLLER_UI_H
#define _GUI_VESC_CONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Home.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_battery_android_0_45dp_1f1f1f_fill0_wght400_grad0_opsz48_png);   // assets/battery_android_0_45dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE( ui_img_pin_road_2_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png);   // assets/pin_road_2_35dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE( ui_img_home_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png);   // assets/home_35dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE( ui_img_info_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png);   // assets/info_35dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE( ui_img_settings_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png);   // assets/settings_35dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
