// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: GUI_vesc_controller

#ifndef _GUI_VESC_CONTROLLER_UI_COMP_HOOK_H
#define _GUI_VESC_CONTROLLER_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
