// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: GUI_vesc_controller

#include "ui.h"

lv_obj_t *uic_NetworkInfo;
lv_obj_t *uic_PassInfo;
lv_obj_t *uic_SSIDInfo;
lv_obj_t *uic_InfoText;
lv_obj_t *uic_PotPosition;
lv_obj_t *uic_SliderPotPosition;
lv_obj_t *uic_CompasAngle;
lv_obj_t *uic_SwitchEnable;
lv_obj_t *uic_Distance;
lv_obj_t *uic_IMGDistance;
lv_obj_t *uic_IMGBattery;
lv_obj_t *uic_Batterlevel;
lv_obj_t *uic_ArcSpeed;
lv_obj_t *uic_Home;
lv_obj_t *ui_Home = NULL;lv_obj_t *ui_ArcSpeed = NULL;lv_obj_t *ui_Speed = NULL;lv_obj_t *ui_Batterlevel = NULL;lv_obj_t *ui_IMGBattery = NULL;lv_obj_t *ui_IMGDistance = NULL;lv_obj_t *ui_Distance = NULL;lv_obj_t *ui_SwitchEnable = NULL;lv_obj_t *ui_CompasAngle = NULL;lv_obj_t *ui_SliderPotPosition = NULL;lv_obj_t *ui_PotPosition = NULL;lv_obj_t *ui_InfoText = NULL;lv_obj_t *ui_SSIDInfo = NULL;lv_obj_t *ui_PassInfo = NULL;lv_obj_t *ui_NetworkInfo = NULL;
// event funtions
void ui_event_ArcSpeed( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Speed, target, "", "km/h");
}
}

void ui_event_SliderPotPosition( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_PotPosition, target, "Pot-Position: ", "");
}
}

// build funtions

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ArcSpeed = lv_arc_create(ui_Home);
lv_obj_set_width( ui_ArcSpeed, 122);
lv_obj_set_height( ui_ArcSpeed, 121);
lv_obj_set_x( ui_ArcSpeed, 1 );
lv_obj_set_y( ui_ArcSpeed, 43 );
lv_obj_set_align( ui_ArcSpeed, LV_ALIGN_TOP_MID );
lv_arc_set_range(ui_ArcSpeed, 0,20);
lv_arc_set_value(ui_ArcSpeed, 16);
lv_obj_set_style_arc_width(ui_ArcSpeed, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcSpeed, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcSpeed, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcSpeed, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcSpeed, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Speed = lv_label_create(ui_ArcSpeed);
lv_obj_set_width( ui_Speed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed, -2 );
lv_obj_set_y( ui_Speed, 20 );
lv_obj_set_align( ui_Speed, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed,"16 km/h");
lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Batterlevel = lv_label_create(ui_Home);
lv_obj_set_width( ui_Batterlevel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Batterlevel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Batterlevel, -110 );
lv_obj_set_y( ui_Batterlevel, -90 );
lv_obj_set_align( ui_Batterlevel, LV_ALIGN_CENTER );
lv_label_set_text(ui_Batterlevel,"78%");
lv_obj_set_style_text_font(ui_Batterlevel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IMGBattery = lv_img_create(ui_Home);
lv_img_set_src(ui_IMGBattery, &ui_img_battery_android_0_45dp_1f1f1f_fill0_wght400_grad0_opsz48_png);
lv_obj_set_width( ui_IMGBattery, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_IMGBattery, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_IMGBattery, -109 );
lv_obj_set_y( ui_IMGBattery, -90 );
lv_obj_set_align( ui_IMGBattery, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_IMGBattery, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_IMGBattery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_IMGDistance = lv_img_create(ui_Home);
lv_img_set_src(ui_IMGDistance, &ui_img_pin_road_2_35dp_1f1f1f_fill0_wght400_grad0_opsz40_png);
lv_obj_set_width( ui_IMGDistance, LV_SIZE_CONTENT);  /// 35
lv_obj_set_height( ui_IMGDistance, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_IMGDistance, -115 );
lv_obj_set_y( ui_IMGDistance, -4 );
lv_obj_set_align( ui_IMGDistance, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_IMGDistance, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_IMGDistance, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Distance = lv_label_create(ui_Home);
lv_obj_set_width( ui_Distance, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Distance, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Distance, -110 );
lv_obj_set_y( ui_Distance, 20 );
lv_obj_set_align( ui_Distance, LV_ALIGN_CENTER );
lv_label_set_text(ui_Distance,"14 km");

ui_SwitchEnable = lv_switch_create(ui_Home);
lv_obj_set_width( ui_SwitchEnable, 90);
lv_obj_set_height( ui_SwitchEnable, 30);
lv_obj_set_x( ui_SwitchEnable, 74 );
lv_obj_set_y( ui_SwitchEnable, -91 );
lv_obj_set_align( ui_SwitchEnable, LV_ALIGN_CENTER );
lv_obj_set_style_border_color(ui_SwitchEnable, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SwitchEnable, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SwitchEnable, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SwitchEnable, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_SwitchEnable, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_SwitchEnable, 1, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_SwitchEnable, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SwitchEnable, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_border_color(ui_SwitchEnable, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SwitchEnable, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SwitchEnable, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_CompasAngle = lv_label_create(ui_Home);
lv_obj_set_width( ui_CompasAngle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CompasAngle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CompasAngle, 98 );
lv_obj_set_y( ui_CompasAngle, 20 );
lv_obj_set_align( ui_CompasAngle, LV_ALIGN_CENTER );
lv_label_set_text(ui_CompasAngle,"320 Deg");

ui_SliderPotPosition = lv_slider_create(ui_Home);
lv_slider_set_range(ui_SliderPotPosition, -100,100);
lv_slider_set_value( ui_SliderPotPosition, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderPotPosition)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderPotPosition, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_SliderPotPosition, 5);
lv_obj_set_width( ui_SliderPotPosition, lv_pct(90));
lv_obj_set_x( ui_SliderPotPosition, 0 );
lv_obj_set_y( ui_SliderPotPosition, 37 );
lv_obj_set_align( ui_SliderPotPosition, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SliderPotPosition, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderPotPosition, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderPotPosition, lv_color_hex(0x0C0909), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderPotPosition, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SliderPotPosition, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderPotPosition, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderPotPosition, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PotPosition = lv_label_create(ui_Home);
lv_obj_set_width( ui_PotPosition, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PotPosition, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PotPosition, 0 );
lv_obj_set_y( ui_PotPosition, 56 );
lv_obj_set_align( ui_PotPosition, LV_ALIGN_CENTER );
lv_label_set_text(ui_PotPosition,"Pot-Position: 0");

ui_InfoText = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_InfoText);
lv_obj_set_height( ui_InfoText, 41);
lv_obj_set_width( ui_InfoText, lv_pct(98));
lv_obj_set_x( ui_InfoText, 0 );
lv_obj_set_y( ui_InfoText, -10 );
lv_obj_set_align( ui_InfoText, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_InfoText,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_InfoText, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_InfoText, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SSIDInfo = lv_label_create(ui_InfoText);
lv_obj_set_width( ui_SSIDInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SSIDInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SSIDInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_SSIDInfo,"SSID: Hiking-trailer");
lv_obj_set_style_text_font(ui_SSIDInfo, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PassInfo = lv_label_create(ui_InfoText);
lv_obj_set_width( ui_PassInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PassInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PassInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_PassInfo,"Pass: Hiking-pass");
lv_obj_set_style_text_font(ui_PassInfo, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NetworkInfo = lv_label_create(ui_InfoText);
lv_obj_set_width( ui_NetworkInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NetworkInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_NetworkInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_NetworkInfo,"Visit: hiking-trailer.local");
lv_obj_set_style_text_font(ui_NetworkInfo, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ArcSpeed, ui_event_ArcSpeed, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderPotPosition, ui_event_SliderPotPosition, LV_EVENT_ALL, NULL);
uic_Home = ui_Home;
uic_ArcSpeed = ui_ArcSpeed;
uic_Batterlevel = ui_Batterlevel;
uic_IMGBattery = ui_IMGBattery;
uic_IMGDistance = ui_IMGDistance;
uic_Distance = ui_Distance;
uic_SwitchEnable = ui_SwitchEnable;
uic_CompasAngle = ui_CompasAngle;
uic_SliderPotPosition = ui_SliderPotPosition;
uic_PotPosition = ui_PotPosition;
uic_InfoText = ui_InfoText;
uic_SSIDInfo = ui_SSIDInfo;
uic_PassInfo = ui_PassInfo;
uic_NetworkInfo = ui_NetworkInfo;

}

void ui_Home_screen_destroy(void)
{
   if (ui_Home) lv_obj_del(ui_Home);

// NULL screen variables
uic_Home= NULL;
ui_Home= NULL;
uic_ArcSpeed= NULL;
ui_ArcSpeed= NULL;
ui_Speed= NULL;
uic_Batterlevel= NULL;
ui_Batterlevel= NULL;
uic_IMGBattery= NULL;
ui_IMGBattery= NULL;
uic_IMGDistance= NULL;
ui_IMGDistance= NULL;
uic_Distance= NULL;
ui_Distance= NULL;
uic_SwitchEnable= NULL;
ui_SwitchEnable= NULL;
uic_CompasAngle= NULL;
ui_CompasAngle= NULL;
uic_SliderPotPosition= NULL;
ui_SliderPotPosition= NULL;
uic_PotPosition= NULL;
ui_PotPosition= NULL;
uic_InfoText= NULL;
ui_InfoText= NULL;
uic_SSIDInfo= NULL;
ui_SSIDInfo= NULL;
uic_PassInfo= NULL;
ui_PassInfo= NULL;
uic_NetworkInfo= NULL;
ui_NetworkInfo= NULL;

}
